admi/urls.py
from django.shortcuts import render
from django.urls import path
from . import views
app_name = 'admi'
# Create your views here.
urlpatterns = [
path('', views.dashboard, name='dashboard'),
path('connexion/', views.user_login, name='connexion'),
path('deconnexion/', views.deconnexion, name='deconnexion'),
path('init_password/', views.changepassword, name='init_password'),    
path('register/', views.register, name='register'),   
path('employe/liste/', views.employe_list, name='employe_list'),
path('employe/<pk>/liste/', views.employe_list2, name='employe_list_filtre'),
# path('employe/ajouter/', views.employe_ajouter.as_view(), name='employe_ajouter'),
path('employe/supprimer/<pk>/', views.employe_supprimer.as_view(),name='employe_supprimer'),
path('employe/<pk>/update', views.EmployeUpdateView.as_view(),name='employe_modifier'), 
path('employe/<pk>/deactivate', views.EmployeDesactivateView.as_view(),name='employe_deactiver'), 
path('employe/<pk>/conge', views.demander_conge,name='employe_conge'),
path('employe/<pk>/liste', views.liste_demander_conge,name='liste_demander_conge'),
path('employe/<pk>/<str:period>/liste', views.liste_demander_conge,name='liste_demander_conge_filtre'),
path('employe/traiter-demande', views.trait_demande_conge,name='trait_demande_conge'),
path('employe/<pk>/traiter-demande_filtre', views.trait_demande_conge_filtre,name='trait_demande_conge_filtre'),
path('employe/<str:id>/<str:nbr>/repondre-demande', views.conge_repondre,name='conge_repondre'),
]

admi_wps/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('admi.urls', namespace='admi')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

admi/forms.py
from django import forms
from .models import *
from django.forms.formsets import BaseFormSet
from django.forms.models import inlineformset_factory, formset_factory, modelformset_factory
from django.contrib.admin.widgets import AdminDateWidget
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.contrib.admin.widgets import AdminDateWidget


class LoginForm(forms.Form):
    nom_d_utilisateur = forms.CharField()
    mot_de_passe = forms.CharField(widget=forms.PasswordInput)

class changepwd(forms.Form):
    Ancien_mot_de_passe = forms.CharField()
    Nouveau_mot_de_passe = forms.CharField(widget=forms.PasswordInput)
    Confirmer_nouveau_mot_de_passe = forms.CharField(widget=forms.PasswordInput)

class EmployeAjoutForm(forms.ModelForm):
    class Meta:
        model = Employe
        exclude = ['actif',]


class employe_consult(forms.ModelForm):
    class Meta:
        model = Employe
        fields = ['user',]


class EmployeUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, label='Nom et prénom')
    email = forms.EmailField(max_length=254, required=True, label='Email')
    GRADE_CHOICES = Employe.grade[:6]
    fonction = forms.ChoiceField(choices=GRADE_CHOICES, label='Fonction')
    class Meta:
        model = Employe
        fields = [
            # "user__first_name",
            "fonction",
            # "user__email",
            "phone",

            
        ]

    solde_conge = forms.DecimalField(required=False)
    solde_conge_maladie = forms.DecimalField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Populate solde_conge field with the current value

        if self.instance and self.instance.nbrEmp.exists():
            self.fields['solde_conge'].initial = self.instance.nbrEmp.last().solde_conge
            self.fields['solde_conge_maladie'].initial = self.instance.nbrEmp.last().solde_conge_maladie
            self.fields['first_name'].initial = self.instance.user.first_name
            self.fields['email'].initial = self.instance.user.email
class EmployeDesactivateForm(forms.ModelForm):
    class Meta:
        model = Employe
        fields = [
            "actif", 
                    ]

class UserRegistrationForm(forms.ModelForm):

  
    phone = forms.CharField(validators=[RegexValidator(regex=r'^\d{8}$', message="Entrer un numéro de 8 chiffres")], required=True)
    password = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Resaisir password',widget=forms.PasswordInput)
    
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']
        labels = {
            'first_name': 'Nom & prénom',

        }
    # def clean_password2(self):
    #     cd = self.cleaned_data
    #     if cd['password'] != cd['password2']:
    #         raise forms.ValidationError('Les mots de passe ne sont pas identiques.')
    #     return cd['password2']
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['first_name'].required = True
        self.fields['email'].required = True
     
        for fieldname in ['username',]:
            self.fields[fieldname].help_text = None

 
   
 
class ddecongeForm(forms.ModelForm):
    
    class Meta:
        model = PasserConge
        exclude = [
            "employee", "Accepte" ,"Refuse"
                    ]
        widgets={
            'DateDebut': forms.DateInput(
                format=('%d/%m/%Y'),
                
                attrs={'class': 'form-control', 
                        
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }
                      
                      ),
            'duree':forms.TextInput(
                attrs={"id":"id_duree"}),
            'DateFin': forms.DateInput(
                format=('%d/%m/%Y'),
                attrs={'class': 'form-control', 
                        'readonly' : 'readonly',
                       'type': 'date'  # <--- IF I REMOVE THIS LINE, THE INITIAL VALUE IS DISPLAYED
                      }),
                      

            }
        labels = {
            'DateDebut': 'Date Début du congé',
            'DateFin': 'Date Fin du congé',
            'duree': 'Durée du congé',
        }
        
    def __init__(self, *args, **kwargs):
    
        super().__init__(*args, **kwargs)
        self.fields['DateDebut'].widget.attrs['onchange'] = 'update_duration()'
        self.fields['duree'].widget.attrs['onchange'] = 'update_duration()'
        
        # self.fields['duree'].readonly = True

admi/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Count,Q,Sum,F,ExpressionWrapper,Case, Value, When,Max,Subquery,OuterRef,FloatField
from .models import *
from .forms import *
from django.urls import reverse_lazy,reverse
from django.shortcuts import render, get_object_or_404,redirect
from django.views.generic import CreateView,UpdateView,DeleteView
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
from django.views.generic.edit import FormView
from datetime import date,datetime
from django.db.models.functions import (
    ExtractDay, ExtractMonth, ExtractQuarter, ExtractWeek,
     ExtractIsoWeekDay, ExtractWeekDay, ExtractIsoYear, ExtractYear,
 )
from django.db.models import Count
from django.db import IntegrityError, transaction
from django.db.models.functions import Cast
from django.db.models import IntegerField,DecimalField,CharField
from django.contrib.auth import authenticate, login, logout
from datetime import timedelta,date
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.db.models import ProtectedError
from django.core.mail import send_mail


def dashboard(request):
    #seuil = Produit.objects.filter(quantite_stock__lte = F('seuil'))
    annee_en_cours = ExtractYear(date.today())
    enconge = PasserConge.objects.filter(Accepte=True, Refuse=False,DateDebut__year= annee_en_cours,DateFin__gt=date.today()) 

    query = request.GET.get('q')
    request.session['recherche'] = query
    if query:
        emp=Employe.objects.filter(
            Q(user__first_name__icontains=query)).exclude(fonction='Administrateur'

            ).distinct()

        cg=PasserConge.objects.filter(
            employee__user__first_name__icontains=query).exclude(employee__fonction='Administrateur'
            
            ).distinct()



    return render(request, 'dashboard.html', locals())

def user_login(request):
    next = request.POST.get('next', request.GET.get('next', ''))

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['nom_d_utilisateur'], password=cd['mot_de_passe'])
            if user is not None:

                login(request, user)
                request.session['utilisateur'] = cd['nom_d_utilisateur']
                request.session['mot_de_passe'] = cd['mot_de_passe']
                msg = "Vous êtes maintenant connecté."


                

                messages.success(request, msg)
                if next:
                    return HttpResponseRedirect(next)

            else:
                messages.warning(request, "Vérifier vos paramètres de connexion.")
            return redirect('admi:dashboard')
    else:
        form = LoginForm()
        ctx = {'form': form, 'next': next}
    return render(request, 'connexion.html', locals())


@login_required
def deconnexion(request):
    logout(request)
    messages.success(request, f'Vous avez été deconnecté')
    return redirect('admi:connexion')


def register(request):
    if request.method == 'POST':

            
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():               
            if User.objects.filter(username=user_form.cleaned_data['username']).exists():
                messages.warning(request, "Ce nom d'utilisateur est déjà pris.")
            elif not user_form.cleaned_data['phone'].isdigit() or len(user_form.cleaned_data['phone']) != 8:
                messages.warning(request, "Le numéro de téléphone doit comporter 8 chiffres.")              
            elif User.objects.filter(email=user_form.cleaned_data['email']).exists():
                messages.warning(request, "Cet email est déjà utilisé.")   
            # elif not  validate_email(user_form.cleaned_data['email']) :
            #     messages.warning(request, "Veuillez choisir un email valide.")                                        
            elif user_form.cleaned_data['password'] != user_form.cleaned_data['password2']:
                messages.warning(request, "Les mots de passe doivent être identiques.")
            else:    
                new_user = user_form.save(commit=False)
                new_user.set_password(
                user_form.cleaned_data['password'])
           
                new_user.save()
                Employe.objects.create(user=new_user,phone=user_form.cleaned_data['phone'])
                messages.success(request, f'Votre compte à été créée avec succés')
                return redirect('admi:dashboard')
    else:
        user_form = UserRegistrationForm()
    return render(request,'register.html',{'user_form':user_form})

@login_required(redirect_field_name=None)
def changepassword(request):
    if request.method == 'POST':
        form = changepwd(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['Ancien_mot_de_passe'] != request.session['mot_de_passe']:
                messages.warning(request, "Vérifier votre ancien mot de passe.")
                return redirect('admi:deconnexion')
            else:
                if cd['Nouveau_mot_de_passe'] != cd['Confirmer_nouveau_mot_de_passe']:
                    messages.warning(request, "Les mots de passe ne correspondent pas. Opération avortée")
                    return redirect(reverse('admi:changepassword'))
                else:
                    user = request.user
                    user.set_password(form.cleaned_data['Nouveau_mot_de_passe'])
                    user.save()
                    update_session_auth_hash(request, user)
                    messages.success(request, "mot de passe changé.")
                    return redirect(reverse('admi:connexion'))
    else:
        form = changepwd()
    return render(request, 'change_password.html', {'form': form})


@method_decorator(staff_member_required, name='dispatch')
class employe_ajouter(CreateView):
    model = Employe
    form_class = EmployeAjoutForm
    template_name = "Employe_ajouter.html"
    def get_success_url(self):
        messages.success(self.request,f'Employé ajouté avec succés')
        return (reverse('admi:employe_list'))

@method_decorator(staff_member_required, name='dispatch')
class employe_supprimer(DeleteView):
    model = Employe
  
    template_name = "employe_supprimer.html"
    def get_success_url(self):
        messages.success(self.request,f'Employé supprimé avec succés')
        return (reverse('admi:employe_list'))



@method_decorator(login_required, name='dispatch')    
class EmployeUpdateView(UpdateView):
    model = Employe
    form_class = EmployeUpdateForm
    template_name = "employe_modifier.html"
    context_object_name = "emp"

    def get_success_url(self):
        messages.success(self.request,f'Employé mis à jour avec succés')
        return (reverse('admi:employe_list'))
    def form_valid(self, form):
        # Handle form validation and save logic here
        if form.is_valid():
            employe = form.save(commit=False)
            
            # Access the new value of solde_conge from the form's cleaned data
            new_solde_conge = form.cleaned_data['solde_conge']
            new_solde_conge_maladie = form.cleaned_data['solde_conge_maladie']
            new_nom =form.cleaned_data['first_name']
            new_email= form.cleaned_data['email']

            
              
            employe.user.first_name=new_nom

            if User.objects.filter(email=new_email).exclude(username=employe.user.username).exists():
                messages.warning(self.request, "Cet email est déjà pris.")
                return self.form_invalid(form)  # Retourne form_invalid si l'e-mail n'est pas unique
            
            employe.user.email =new_email
                
            if employe.nbrEmp.exists():
                compte_instance = employe.nbrEmp.last()
                compte_instance.solde_conge = new_solde_conge
                compte_instance.solde_conge_maladie = new_solde_conge_maladie
                compte_instance.save()

            employe.user.save()   
            employe.save()
            # Vérifier si le formulaire provient du formset
            if form.is_bound:
                messages.success(self.request, 'Employé mis à jour avec succès')
                
                return HttpResponseRedirect(self.get_success_url())

           
            
            return super().form_valid(form)



@method_decorator(staff_member_required, name='dispatch')
class EmployeDesactivateView(UpdateView):
    model = Employe
    form_class = EmployeDesactivateForm
    template_name = "employe_modifier.html"
    context_object_name = "emp"


    def get_success_url(self):
        messages.success(self.request,f'Employé désactivé avec succés')
        return (reverse('admi:employe_list'))


@staff_member_required
def employe_list(request):

    annee_en_cours = ExtractYear(date.today())
    employe = Employe.objects.filter(actif=True).exclude(fonction='Administrateur')

    employes_avec_nombre_conges = employe.annotate(
        nombre_conges_annuels=Sum(
            Case(
                When(CongEmp__DateDebut__year=annee_en_cours, CongEmp__Accepte=True, CongEmp__type_conge='Congé Annuel',  then=F('CongEmp__duree')),default=0,
                output_field=DecimalField()
            )
        ),
        nombre_conges_maladie=Sum(
            Case(

admi/templates/Employe_ajouter.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>Ajouter Employé</title>{% endblock %}
{% block content %}
    <h1>Ajouter Employe</h1>
    <form action="." method="post" >
        {% csrf_token %}
        {{ form.as_p }}



 <a href="{% url 'admi:employe_list' %}" class="btn btn-warning">Liste des employés</a>
        <input type="submit" class="btn btn-success" value="Ajouter">
  
    </form>




{% endblock %}

admi/templates/conge_dde_confirm.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>Traitee demande congé</title>{% endblock %}


{% block content %}
<div>

    {{dde.DateDebut}} conge annu={{dde.employee.nbrEmp.last.solde_conge}} et de conge maledie =  {{dde.employee.nbrEmp.last.solde_conge_maladie}}

nbr = {{nbr}}

</div>    
{% endblock %}

admi/templates/conge_trait_dde _filtre.html
{% extends "base.html" %}
{% load static %}
{% block title %}<title>Traiter Demande congé</title>{% endblock %}
{% block content %}

<style>
    th{vertical-align:middle;}
    td,th,tr{border:solid pink;text-align:center}
    a{display:button}
    </style>
<div class="content">
<p>Congés pris et congés restant concernant l'année en cours</p>
    <table class="table table-bordered">
<tr>
<th rowspan="2">date demande</th>
<th rowspan="2">Nom employe</th>    
<th rowspan="2">Type conge</th>
<th rowspan="2">Date début</th>
<th rowspan="2">Date Fin</th>
<th rowspan="2">Durée</th>
<th colspan="2">Congé pris</th>
<th colspan="2">Congé restant</th>

<th rowspan="2">Refuser ?</th>
<th rowspan="2" >Accepter ?</th>
</tr> 
<tr>
<th >Annuel </th>
<th >Maladie </th>    
<th >Annuel </th>
<th >Maladie </th>
</tr>    
{% for  ab in dde %}  

    <tr>
        <td>{{ab.DateDemande}}</td>
        <td>{{ab.employee.user.first_name}}</td>
        <td>{{ab.type_conge}}</td>
        <td>{{ab.DateDebut}}</td>
        <td>{{ab.DateFin}}</td>
        <td>{{ab.duree}}</td>
        <td>{{ab.nombre_conges_annuels}}</td>
        <td>{{ab.nombre_conges_maladie}}</td>   
        <td>{{ab.employee.nbrEmp.last.solde_conge}}</td>
        <td>{{ab.employee.nbrEmp.last.solde_conge_maladie}}</td>
         {% if not ab.Accepte and not ab.Refuse %} 
        <td><a class="cinfirma" href="{% url 'admi:conge_repondre' ab.id 'ref' %}"><button type="button">Refuser</button></a></td>
        <td><a class="confirma" href="{% url 'admi:conge_repondre' ab.id 'acc' %}"><button type="button">Accepter</button></a></td>
        {%endif%}
    </tr>
    
{% endfor %}
</table></div>

</div>



<script>
    document.addEventListener('DOMContentLoaded', function () {
        let linksRefuser = document.querySelectorAll('.cinfirma');
        let linksAccepter = document.querySelectorAll('.confirma');

        for (let link of linksRefuser) {
            link.addEventListener('click', function (event) {
                event.preventDefault();
                let accepted = confirm("Etes-vous sûr de vouloir refuser cette demande?");
                if (accepted) {
                    window.location.href = link.href;
                }
            });
        }

        for (let link of linksAccepter) {
            link.addEventListener('click', function (event) {
                event.preventDefault();
                let accepted = confirm("Etes-vous sûr de vouloir accepter cette demande?");
                if (accepted) {
                    window.location.href = link.href;
                }
            });
        }
    });
</script>



{% endblock %}

admi/templates/connexion.html
{% extends "base.html" %}

{% block title %}Connexion{% endblock %}

{% block content %}
<style>


</style>
    <h1>Connexion</h1><br><br>
    <p>Saisir votre nom d'utilisateur et votre mot de passe:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}



        <p> <input type="submit" class="btn btn-success" value="Connexion"></p>
         <input type="hidden" name="next" value="{{ next }}"/>

    </form>


  
{% endblock %}

admi/templates/dashboard.html
{% extends "base.html" %}
{% block title %}Tableau de bord{% endblock %}



<div class="content">
{% block content %}

{% if request.user.is_staff %}

<div class="post-content">
Employé(s) en congé:
<ul>
{% if enconge %}
{% for ab in enconge %}
<li>{{ab.employee.user.first_name}} reprend le travail le {{ab.DateFin}}</li>
{% endfor%}
{%else%}
<li>Aucun employé</li>
{% endif %}
</ul>
</div>
{% if query %}

{% if emp %}
<div class="post-content">
<h6>Employés:</h6>
<ul>
{% for ab in emp %}
<li><a href="{% url 'admi:employe_list_filtre' ab.id %}"> &nbsp;{{ab.user.first_name}} &nbsp;  </a>
{% endfor %} 
</ul>
</div>
{% endif %} 

{% if cg %}
<div class="post-content">
<h6>Congés:</h6>
<ul>
  {% for ab in cg %}
    <li>
      <a href="{% url 'admi:trait_demande_conge_filtre' ab.id %}">
        &nbsp;{{ ab.employee.user.first_name }} &nbsp; {{ ab.duree }} jours
        {% if not ab.Accepte and not ab.Refuse %}
          (En instance)
        {% elif ab.Accepte %}
          (Accepté)
        {% elif ab.Refuse %}
          (Refusé)
        {% endif %}
        à partir de {{ab.DateDebut}}
        
      </a>
    </li>
  {% endfor %}
</ul>
</div>
{% endif %} 

{% endif %}

{% endif %}







{% endblock %}
</div>

admi/templates/employe_list.html
{% extends "base.html" %}

{% block title %}<title>Liste des employés</title>{% endblock %}




{% block content %}
<style>
th{vertical-align:middle;}
td,th,tr{border:solid pink;text-align:center}
</style>
<h3>Liste de(s)  employés(s) </h3>
<br>

<p>Congés pris et congés restant concernant l'année en cours</p>
<div class="content">

    <table class="table table-bordered">
<tr>
<th rowspan="2">Nom employé</th>
<th rowspan="2">Fonction</th>    
<th rowspan="2">Téléphone</th>
<th rowspan="2">Email</th>
<th rowspan="2">Date embauche</th>
<th colspan="2">Congé pris</th>
<th colspan="2">Congé restant</th>
<th rowspan="2">Historique ?</th>
<th rowspan="2">Modifier ?</th>
<th rowspan="2">Désactiver ?</th>
<th rowspan="2">Supprimer ?</th>
</tr> 
<tr>
    <th>Annuel</th>
    <th>Maladie</th>  
    <th>Annuel</th>  
    <th>Maladie</th>

    </tr>
{% for ab in emp %}   
<tr>
<td>{{ab.user.first_name}}</td>
<td>{{ab.fonction}} </td>
<td>{{ab.phone}} </td>
<td>{{ab.user.email}} </td>
<td>{{ab.date_embauche}} </td>
<td>{{ab.nombre_conges_annuels}}</td>
<td>{{ab.nombre_conges_maladie}}</td>
<td>{{ab.nbrEmp.last.solde_conge}} </td>
<td>{{ab.nbrEmp.last.solde_conge_maladie}} </td>


<td><a href="{% url 'admi:liste_demander_conge' ab.id %}"><button type="button">Historique</button></a></td>
<td><a href="{% url 'admi:employe_modifier' ab.id%}"><button type="button">Modifier</button></a></td>
<td><a href="{% url 'admi:employe_deactiver' ab.id%}"><button type="button">Désactiver</button></a></td>
<td><a href="{% url 'admi:employe_supprimer' ab.id%}"><button type="button">Supprimer</button></a></td>

</tr>
{% endfor %}
</table></div>

</div>






{% endblock %}

admi/templates/employe_modifier.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
<title>{{ emp.nom_employe }}</title>
 {% endblock %}

{% block content %}

<h1 style="margin-bottom:5%">{{ emp.nom_employe }}</h1>
<form method="post" enctype='multipart/form-data' > 
    {% csrf_token %} 
    {{ form.as_p }} 
    <input type="submit" class="btn btn-outline-success" value="Enregistrer"> 
</form> 

<br>

{% endblock %}

admi/templates/latest.html
<ul>
    {% for post in getp %}
    <li>
    <a href="{% url 'admi:trait_demande_conge_filtre' post.pk  %}">{{ post.employee.user.first_name }} ({{post.duree}} jours)</a>
    </li>
    {% endfor %}
    </ul>

admi/templates/menu.html
{% load static %}
<ul class="d-flex align-items-center">
{% if request.user.is_authenticated %}





      

        


          
        <li class="nav-item dropdown pe-3">
          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <span>Profil </span>
            <span class="d-none d-md-block dropdown-toggle ps-2"> {{request.user}}</span>
          </a><!-- End Profile Iamge Icon -->
          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'admi:init_password' %}">
              <i class="bi bi-gear"></i>
              <span>Changer mon mot de passe</span>
              </a>
              <li>
                <hr class="dropdown-divider">
              </li>
                <a class="dropdown-item" href="{% url 'admi:deconnexion' %}">
              <i class="bi bi-box-arrow-right"></i>
              <span>Déconnexion</span>
              </a>
              <li>
                <hr class="dropdown-divider">
              </li>
                <a class="dropdown-item" href="">
                <i class="bi bi-x-octagon-fill"></i>
              <span>Supprimer compte</span>
            </a>



          {% if not request.user.is_staff %}
          <li>
            <hr class="dropdown-divider">
          </li>
            <a class="dropdown-item" href="{% url 'admi:employe_conge' request.user.uzer.id%}">
            <i class="bi bi-hourglass-split"></i>
          <span>Demande conge</span>
        </a>

        <li>
          <hr class="dropdown-divider">
        </li>
          <a class="dropdown-item" href="{% url 'admi:liste_demander_conge' request.user.uzer.id %}">
          <i class="bi bi-journal-text"></i>
        <span>Liste des Demandes de congés</span>
      </a>{% endif %}

            </li>
        </ul>
        </li>




          
          {% if request.user.is_staff %}
    
          <li class="nav-item dropdown pe-3">
            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
              <span>E</span>
              <span class="d-none d-md-block dropdown-toggle ">mployés</span>
            </a><!-- End Profile Iamge Icon -->
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'admi:employe_list' %}">
                    <i class="bi bi-card-checklist"></i>
                <span>Liste des employés(Modifier/Consulter/Supprimer)</span>
                </a>
                <li>
                  <hr class="dropdown-divider">
                </li>
                  <a class="dropdown-item" href="{% url 'admi:register' %}">
                <i class="bi bi-car-front"></i>
                <span>Ajouter un employé</span>
                </a>


                <hr class="dropdown-divider">
              </li>
                <a class="dropdown-item" href="{% url 'admi:trait_demande_conge' %}">
              <i class="bi bi-broadcast-pin"></i>
              <span>Traiter demandes de congés</span>
              </a>



              
                </ul>
          </li>
      
          
          
          {% endif %}

 


          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
      {% else %}
 




      <li class="nav-item dropdown pe-3">
        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <span>C</span>
          <span >onnexion</span>
        </a><!-- End Profile Iamge Icon -->
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">



              <li>
                <a class="dropdown-item" href="{% url 'admi:connexion' %}">
                    <i class="bi bi-unlock"></i>
                <span>Connexion</span>
                </a>
    
                <li>
                  <hr class="dropdown-divider">
                </li>
                  <a class="dropdown-item" href="{% url 'admi:register' %}">
                <i class="bi bi-steam"></i>
                <span>Créer un compte</span>
                </a>

                <li>
                    <hr class="dropdown-divider">
                  </li>
                    <a class="dropdown-item" href="{% url 'admi:init_password' %}">
                  <i class="bi bi-upc-scan"></i>
                  <span>Initialiser mon mot de passe</span>
                  </a>

                  
            </ul>
      </li>
    </ul>
{% endif %}